### ISSUE TITLE
Error in start

### ISSUE THREAD

**Issue by ghost** [randombyte-developer/holograms#31]
Occurred in the last version of Sponge Forge, API 8

> [18:09:17] [Server thread/WARN] [Sponge]: holograms: It is no longer required to include the plugin id when specifying a Key id through Key.Builder#id. This is deprecated and may be removed later. The plugin id will be retrieved from the current PluginContainer in the cause stack. Key: SpongeKey{name=Is Hologram, id=holograms:is-hologram, valueToken=org.spongepowered.api.data.value.mutable.Value<java.lang.Boolean>, elementToken=java.lang.Boolean, query=IsHologram}
[18:09:18] [Server thread/ERROR] [Sponge]: Could not pass FMLPreInitializationEvent to Plugin{id=holograms, name=Holograms, version=3.1.5, authors=[RandomByte], source=.\mods\holograms-3.1.5.jar}
java.lang.NoClassDefFoundError: de/randombyte/holograms/data/HologramData
        at de.randombyte.holograms.Holograms.onPreInit(Holograms.kt:52) ~[Holograms.class:?]
        at org.spongepowered.common.event.listener.GamePreInitializationEventListener_Holograms_onPreInit24.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2705-8.0.0-BETA-3302]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2705-8.0.0-BETA-3302]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:420) [SpongeModEventManager.class:1.12.2-2705-8.0.0-BETA-3302]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2705-8.0.0-BETA-3302]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:233) [SpongeImpl.class:1.12.2-2705-8.0.0-BETA-3302]
        at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:246) [SpongeMod.class:1.12.2-2705-8.0.0-BETA-3302]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: de.randombyte.holograms.data.HologramData
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        ... 40 more
Caused by: java.lang.VerifyError: class de.randombyte.holograms.data.HologramData overrides final method toContainer.()Lorg/spongepowered/api/data/DataContainer;
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_181]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        ... 40 more

**Comment by randombyte-developer** [comment]
Please post the whole server log to pastebin and what versions are you running? (Forge and Sponge)

**Comment by ghost** [comment]
Log [here](https://pastebin.com/NR6r8S8W). I'm using Forge 14.23.4.2705 and Sponge 2705-8.0.0-BETA-3302. Holograms 3.1.5

**Comment by randombyte-developer** [comment]
You are using an unstable experimental v8.0.0 build. Use `1.12.2-2705-7.1.0-BETA-3206` or later. https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2

**Comment by ghost** [comment]
Thanks :D
